# Generated by Django 3.0.2 on 2020-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtUser',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('schoolname', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('verification_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dt_user',
                'managed': False,
            },
        ),
    ]
