# Generated by Django 3.0.2 on 2020-08-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dtuser',
            table=None,
        ),
    ]
