# Generated by Django 3.0.2 on 2020-08-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200825_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtuser',
            options={},
        ),
    ]
